# Generated by Django 5.0.6 on 2024-12-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrow_borrow_date_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
